library(shinythemes)
library(shinyWidgets)
library(shiny)
library(shinydashboard)
library(readxl)
library(dplyr)
library(biomaRt)
library(regioneR)
library(readr)
library(data.table)
library(fs)
library(tidyverse)
library(purrr)
library(DT)
library(karyoploteR) 
library(ggplot2)
############
annotation1 <- read_csv("annotation/annotation1.txt")
annotation2 <- read_csv("annotation/annotation2.txt")
full_list <- read_excel("gene-disease/full_list.xlsx")
expression <- read_csv("data/expression.csv")
file_paths_control <- fs::dir_ls("data/snp/control")
file_paths_patient <- fs::dir_ls("data/snp/patient")
annotation1 <- read_csv("annotation/annotation1.txt")